env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - airbnb/hooks
  - plugin:prettier/recommended
settings:
  import/resolver:
    node:
      moduleDirectory:
        - src/
        - node_modules
      extensions:
        - .js
        - .jsx
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules: { react/prop-types: off, react/jsx-props-no-spreading: off }
