name: Run tests
env:
  CI: true
'on':
  push: null
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: Install and test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - run: npm install --package-lock-only
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present
